# Generated by Django 4.1 on 2022-10-16 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0010_remove_post_category_remove_post_user_and_more'),
        ('posts', '0007_alter_post_post_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cocktail.category'),
        ),
    ]
