# Generated by Django 4.1 on 2022-09-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
