# Generated by Django 4.1 on 2022-09-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='Ingredient1',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='Ingredient2',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='Ingredient3',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='Ingredient4',
        ),
    ]
