# Generated by Django 4.1 on 2022-09-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0002_rename_ingredient1_ingredient_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
