# Generated by Django 4.1 on 2022-09-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0003_remove_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='alchole',
            field=models.DecimalField(decimal_places=0, max_digits=100, null=True, verbose_name='Alcohol'),
        ),
    ]
