# Generated by Django 4.1 on 2022-09-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0004_remove_post_description_cocktail_alchole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='alchole',
            field=models.DecimalField(decimal_places=1, max_digits=100, null=True, verbose_name='Alcohol'),
        ),
    ]
