# Generated by Django 4.1 on 2022-09-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0005_alter_cocktail_alchole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='alchole',
            new_name='alcohol',
        ),
    ]
