# Generated by Django 4.1 on 2022-09-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0006_rename_alchole_cocktail_alcohol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='TITLE'),
        ),
    ]
