# Generated by Django 4.1 on 2022-09-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0007_alter_cocktail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Cocktail_name'),
        ),
    ]
