# Generated by Django 4.0.6 on 2022-10-05 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cocktail', '0008_alter_cocktail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='bookmark',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/cocktail/', verbose_name='IMAGE'),
        ),
    ]
